### ISSUE TITLE
refactoring needed - CoinAcceptor and BillValidator

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dharillo/cctalk-net#1]
```
Adding support for bill validators added significant amount of "copypasted" 
code.
Refactoring needed.
```

Original issue reported on code.google.com by `alexus1...@gmail.com` on 24 Apr 2012 at 12:05

**Comment by dharillo** [comment]
Openned a new branch **validators-refactor** to make the refactor.

**Comment by dharillo** [comment]
Refactor complete.
See: https://github.com/dharillo/cctalk-net/pull/6 for more detailed list of the changes done.
